name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: |
          uv sync
          uv python install

      - name: Build standard distribution
        if: matrix.os == 'ubuntu-latest'
        run: uv build

      - name: Build Windows EXE
        if: matrix.os == 'windows-latest'
        run: uv run pyinstaller --windowed --onefile --name "VAULT" main.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Latest
          make_latest: true
          files: dist/*
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.Release }}